services:
  firely:
    image: firely/server:6.7.0
    ports:
      - "4080:4080"
    environment:
      - VONK_PATH_TO_SETTINGS=/app/config
    volumes:
      - ./config:/app/config
      - ./vonk-imported:/app/vonk-imported
      - ./.plugins:/app/plugins:ro
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:7
    command: ["mongod", "--logpath", "/dev/null"]
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  openfhir:
      image: openfhir/openfhir:latest
      container_name: openfhir
      ports:
        - "8083:8080"
      environment:
        - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@mongodb:27017/openfhir?authSource=admin
        - SPRING_DATA_MONGODB_DATABASE=openfhir
        - OPENFHIR_DB_TYPE=mongo
      volumes:
        - ./fhirconnect/:/app/bootstrap/
      depends_on:
        mongodb:
          condition: service_healthy

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_FHIR_API_URL=http://localhost:4080
      - FHIR_API_URL=http://firely:4080
      - PUBLIC_APP_NAME=FHIR-openEHR Integration
      - PUBLIC_APP_VERSION=1.0.0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - firely

volumes:
  mongodb-data:
